project:
  type: website
  # resources:
  #   - "images/twitter-card.png"
  #   - "data"
  # render:
  #   - "*.qmd"
  #   - "!README.qmd"

website:
  page-navigation: true
  title: "Guest Lecture Slides "
  site-url: "https://minnaheim.github.io/dh_guest_lecture/index.html"
  repo-url: https://github.com/minnaheim/dh_guest_lecture
  repo-actions: [edit, issue]

  # page-footer:
  #   left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  #   background: "#426D98"

  # navbar:
  #   background: "#426D98"
  #   pinned: true
  #   align: center


format:
  html:
    theme:
      light: [cosmo, theme.scss]

#     toc: true
#     code-copy: true
#     code-overflow: wrap
#     mainfont: "Open Sans"
#     # include-after-body: plausible.html